const sidebars = {
  userDocsSidebar: [
    {
      type: "autogenerated",
      dirName: "user",
    },
  ],

  developerDocsSidebar: [
    {
      type: "autogenerated",
      dirName: "developer",
    },
  ],
};

export default sidebars;
